// ============================================================
// models/Payroll.model.js
// Stores computed payroll snapshots per employee per period.
//
// Design decisions:
//   SNAPSHOT STRATEGY:
//     salaryType and baseSalary are copied from the Employee
//     record at generation time. Even if the employee's salary
//     changes later, this payroll record is immutable in those
//     fields. This is critical for payroll history integrity.
//
//   PERIOD:
//     Stored as { month, year } sub-document (not a Date range)
//     for intuitive querying and display. The unique index uses
//     dot-notation on these nested fields.
//
//   STATUS MACHINE:
//     draft → approved → paid (forward only)
//     approved → draft (reject/revert)
//     paid is terminal — no transitions allowed.
//
//   CALCULATION FIELDS:
//     All calculated values are stored explicitly on the document.
//     No field is derived at read time — this keeps the snapshot
//     stable and query-performant.
// ============================================================

import mongoose from 'mongoose'

const { Schema, model } = mongoose

export const PAYROLL_STATUSES = ['draft', 'approved', 'paid']

const payrollSchema = new Schema(
  {
    // ── Tenant & Outlet Scope ─────────────────────────────────

    tenantId: {
      type:     Schema.Types.ObjectId,
      ref:      'Tenant',
      required: [true, 'Tenant ID is required'],
    },

    outletId: {
      type:     Schema.Types.ObjectId,
      ref:      'Outlet',
      required: [true, 'Outlet ID is required'],
    },

    employeeId: {
      type:     Schema.Types.ObjectId,
      ref:      'Employee',
      required: [true, 'Employee ID is required'],
    },

    // ── Period ────────────────────────────────────────────────
    // month: 1–12, year: 4-digit integer

    period: {
      month: {
        type:     Number,
        required: [true, 'Period month is required'],
        min:      [1, 'Month must be between 1 and 12'],
        max:      [12, 'Month must be between 1 and 12'],
      },
      year: {
        type:     Number,
        required: [true, 'Period year is required'],
        min:      [2000, 'Year must be 2000 or later'],
      },
    },

    // ── Snapshot: Employee State at Generation Time ───────────
    // These are COPIED from Employee at generation — immutable
    // after creation regardless of future employee changes.

    salaryType: {
      type:     String,
      enum:     ['monthly', 'daily'],
      required: [true, 'Salary type snapshot is required'],
    },

    baseSalary: {
      type:     Number,
      required: [true, 'Base salary snapshot is required'],
      min:      [0, 'Base salary cannot be negative'],
    },

    // ── Attendance Summary ────────────────────────────────────

    workingDays: {
      type:     Number,
      required: [true, 'Working days is required'],
      min:      [1, 'Working days must be at least 1'],
    },

    presentDays: {
      type:     Number,
      required: true,
      default:  0,
      min:      [0, 'Present days cannot be negative'],
    },

    absentDays: {
      type:     Number,
      required: true,
      default:  0,
      min:      [0, 'Absent days cannot be negative'],
    },

    // ── Sales Summary ─────────────────────────────────────────

    totalCupsSold: {
      type:    Number,
      default: 0,
      min:     [0, 'Total cups sold cannot be negative'],
    },

    cupsBonus: {
      type:    Number,
      default: 0,
      min:     [0, 'Cups bonus cannot be negative'],
    },

    // ── Manual Adjustments ────────────────────────────────────
    // Can be set/changed on draft payrolls via the adjust endpoint.

    manualBonus: {
      type:    Number,
      default: 0,
      min:     [0, 'Manual bonus cannot be negative'],
    },

    deductions: {
      type:    Number,
      default: 0,
      min:     [0, 'Deductions cannot be negative'],
    },

    // ── Calculated Totals ─────────────────────────────────────

    salaryEarned: {
      type:     Number,
      required: true,
      default:  0,
    },

    totalPay: {
      type:     Number,
      required: true,
      default:  0,
    },

    // ── Status ────────────────────────────────────────────────

    status: {
      type:     String,
      enum:     {
        values:  PAYROLL_STATUSES,
        message: `Status must be one of: ${PAYROLL_STATUSES.join(', ')}`,
      },
      default:  'draft',
    },

    // ── Audit ─────────────────────────────────────────────────

    generatedBy: {
      type:     Schema.Types.ObjectId,
      ref:      'User',
      required: [true, 'Generated by (userId) is required'],
    },

    approvedBy: {
      type:    Schema.Types.ObjectId,
      ref:     'User',
      default: null,
    },

    generatedAt: {
      type:    Date,
      default: () => new Date(),
    },

    approvedAt: {
      type:    Date,
      default: null,
    },
  },
  {
    timestamps: true,
    versionKey: false,
  }
)

// ── Indexes ───────────────────────────────────────────────────

// PRIMARY UNIQUE CONSTRAINT:
// One payroll per employee per period per tenant.
payrollSchema.index(
  {
    tenantId:      1,
    employeeId:    1,
    'period.month': 1,
    'period.year':  1,
  },
  { unique: true }
)

// List query: tenant → outlet → period
payrollSchema.index({ tenantId: 1, outletId: 1, 'period.year': -1, 'period.month': -1 })

// Status filter within tenant
payrollSchema.index({ tenantId: 1, status: 1 })

const Payroll = model('Payroll', payrollSchema)

export default Payroll
